<%@ Page Language="VB" AutoEventWireup="false" CodeFile="TubeOverride.aspx.vb" Inherits="Tubes_TubeOverride" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Tube Option Overrides</title>
   <link href="StyleSheet.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style1 {}
        .auto-style2 {}
        .newStyle1 {}
        .newStyle2 {
            font-family: Calibri;
            font-size: 18px;
            font-weight: 700;
        }
        .newStyle4 {
            font-weight: 700;
        }
    </style>    
    
     <script>
         function RefreshParent() {
             window.opener.document.getElementById('btnRefresh').click();             
         }
     </script>
     
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <span class="newStyle2"><strong>Tube Overrides for Production #</strong>:
    
        </span>
    
        <asp:Label ID="lblProdNo" runat="server" Text="" CssClass="newStyle2"></asp:Label>
        
        
    
        <span class="newStyle2">
        
        
    
        <br />
        <br />
        </span>
        <span class="newStyle4">
        <asp:Label ID="lblAddNewNote" runat="server" Text="Add an Override" CssClass="newStyle2"></asp:Label>
        </span>
    
        <span class="newStyle2">
        <br />
        </span>
        <span class="newStyle4">
        <asp:TextBox ID="tbOverride" runat="server" CssClass="auto-style2" Height="23px" MaxLength="300" Width="540px"></asp:TextBox>
        </span>
    
        <span class="newStyle2">
        <br />
        </span>
        <span class="newStyle4">
        <span class="newStyle2">Which workstation does this override apply to?<br />
        </span>
        <asp:DropDownList ID="ddlTubeStations" runat="server">
            <asp:ListItem></asp:ListItem>
            <asp:ListItem>Roller</asp:ListItem>
            <asp:ListItem Value="RoundSeamer">Round Seamer</asp:ListItem>
            <asp:ListItem>Brackets</asp:ListItem>
            <asp:ListItem>Repair</asp:ListItem>
            <asp:ListItem>Chines</asp:ListItem>
            <asp:ListItem Value="RollerCT">Center Roller</asp:ListItem>
            <asp:ListItem Value="RoundSeamerCT">Center Round Seamer</asp:ListItem>
            <asp:ListItem Value="BracketsCT">Center Brackets</asp:ListItem>
            <asp:ListItem Value="RepairCT">Center Repair</asp:ListItem>
            <asp:ListItem Value="ChinesCT">Center Chines</asp:ListItem>
        </asp:DropDownList>
        </span>
    
        <span class="newStyle2">
        <br />
        </span>
        <span class="newStyle4">
        <asp:Button ID="btnBoatNote" runat="server" Text="Submit" OnClientClick="RefreshParent();"/>
        </span>
    
        <span class="newStyle2">
        <br />
    
        <br />
        </span>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataSourceID="sdsOverride" CssClass="newStyle1 auto-style1" Width="676px" DataKeyNames="Auto">
            <Columns>
                <asp:BoundField DataField="Auto" HeaderText="Auto" InsertVisible="False" ReadOnly="True" SortExpression="Auto" Visible="False" />
                <asp:BoundField DataField="Override" HeaderText="Override" SortExpression="Note" />
                <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" DataFormatString="{0:d}" >
                <ItemStyle Width="30px" />
                </asp:BoundField>
            </Columns>
        </asp:GridView>
        <br />
        <asp:Button ID="btnClose" runat="server" Text="Close"/>
        <asp:SqlDataSource ID="sdsOverride" runat="server" ConnectionString="<%$ ConnectionStrings:bml_dataConnectionString %>" SelectCommand="SELECT [Auto], [ProdNo], [Override], [Date] FROM [BML_POPREPORTING_TUBEOVERRIDES] WHERE ([ProdNo] = @ProdNo)" DeleteCommand="DELETE FROM [BML_POPREPORTING_TUBEOVERRIDES] WHERE ([Auto] = @Auto)">
            <SelectParameters>
                <asp:ControlParameter ControlID="lblProdNo" Name="ProdNo" PropertyName="Text" Type="String" />
            </SelectParameters>
            <DeleteParameters>
              <asp:Parameter Name="Auto" Type="Int16" />
            </DeleteParameters>
        </asp:SqlDataSource>
    
        <br />
    
    </div>
    </form>
</body>
</html>